# Crane-based derivation for the ezpz-dndz-server binary.
# Called from flake.nix with: import ./server.nix { inherit craneLib commonArgs pkgs; }
#
# The package output is a single self-contained binary:
#   $out/bin/ezpz-dndz-server — the server, with the compiled Elm
#                               frontend embedded into it.
#
# The frontend is built by the `elmFrontend` derivation below and handed to
# the crate build through the `RUST_TEMPLATE_FRONTEND_DIR` environment
# variable, which the server crate's `build.rs` forwards to the `rust_embed`
# `Frontend` type.  Embedding (rather than shipping a sibling asset
# directory) means the deployed binary needs nothing alongside it — there
# is no `--frontend-path` to point at a separate directory.
#
# Elm build: uses pkgs.elmPackages.fetchElmDeps with the elm-srcs.nix and
# registry.dat files generated by elm2nix.  All package fetching happens
# through individual fixed-output derivations, so the build is fully offline
# and hermetic.
#
# When elm.json dependency versions change, regenerate both files:
#   cd frontend
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- convert 2>/dev/null > elm-srcs.nix
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- snapshot
# then commit elm-srcs.nix and registry.dat.
{
  craneLib,
  commonArgs,
  pkgs,
}: let
  elmFrontend = pkgs.stdenv.mkDerivation {
    name = "ezpz-dndz-elm-frontend";
    src = ../../frontend;
    nativeBuildInputs = [pkgs.elmPackages.elm];

    configurePhase = pkgs.elmPackages.fetchElmDeps {
      elmPackages = import ../../frontend/elm-srcs.nix;
      elmVersion = "0.19.1";
      registryDat = ../../frontend/registry.dat;
    };

    buildPhase = ''
      elm make src/Main.elm --optimize --output elm.js
    '';

    installPhase = ''
      mkdir -p $out
      # Ship everything under public/ (fonts, ping.wav, …), not just the
      # three core files — the frontend fetches these as static assets.
      # --no-dereference keeps the dangling bundled-creatures.json symlink
      # from failing the copy; it points outside this derivation's src and
      # is replaced with the real file just below.
      cp -r --no-dereference public/. $out/
      # The public/ copy of bundled-creatures.json is a repo-relative
      # symlink into crates/lib/data (outside this derivation's src), so
      # replace it with the canonical file, pulled into the store as its
      # own path.
      rm -f $out/bundled-creatures.json
      cp ${../../crates/lib/data/bundled-creatures.json} $out/bundled-creatures.json
      # The fresh optimized build replaces whatever dev elm.js the source
      # tree carried (it is gitignored, so normally absent).
      cp elm.js $out/
      # Stamp the script src with the Nix store hash so each build gets a
      # unique URL.  Browsers that cached /elm.js from a previous build will
      # fetch the new /elm.js?v=<hash> URL instead.
      STORE_HASH=$(basename $out | cut -d'-' -f1)
      sed "s|/elm.js|/elm.js?v=$STORE_HASH|g" public/index.html > $out/index.html
    '';
  };
in
  craneLib.buildPackage (commonArgs
    // {
      pname = "ezpz-dndz-server";
      cargoExtraArgs = "-p ezpz-dndz-server";
      # The server crate's build.rs reads this and forwards it to the
      # `rust_embed` `Frontend` type, which bakes the assets into the
      # binary.  Referencing the derivation here also makes it a build
      # dependency, so the Elm bundle is compiled before the crate build
      # runs.
      RUST_TEMPLATE_FRONTEND_DIR = "${elmFrontend}";
    })
